### ISSUE TITLE
Start numbering of pngs from 1 instead of 0

### ISSUE THREAD

**Issue by nautilus7** [cubicibo/ass2bdnxml#3]
Hi, would you consider changing the numbering of the output png files to start from 1 instead of 0?

Since other subtitles formats like SRT or programs like subtitleedit usually start their numbering from 1, it would be easier for the user to identify or relate each png to the corresponding entry in the ASS input.

Thanks.

**Comment by cubicibo** [comment]
Hi,
sorry, no. BDN data is not meant for manual analysis as there can be tens of thousands of PNGs for complex files. The PNG file naming should not matter.

If you dislike the file naming, you can post process the output with a batch script that increments the ID in the filename by one and re-write the XML appropriately.

**Comment by nautilus7** [comment]
I don't want to do any post processing to the bdn/xml or the pngs. I just open a png and check whether the visual style (font size, style, spacing, etc) is what I like/want. This process would be somewhat easier if there is a one-to-one numbering match between the source file (ass) and the output. That's all.
