### ISSUE TITLE
4k support

### ISSUE THREAD

**Issue by dadlklk** [cubicibo/ass2bdnxml#7]
About 2160p UHD: The players upscale the presentation graphics on playback.

It does, but it causes blurry text edges, is it possible to add support for 4k resolution?

**Comment by cubicibo** [comment]
Unfortunately, 2160p PGS is strictly forbidden by BD UHD format and unsupported by BD players. Try as you might, no UHD BD player will decode and show 4K PGS subtitles.

I would say there's no reason to add 2160p output support as you cannot do anything with those files, unless you know of one I am unaware of.

**Comment by dadlklk** [comment]
Use the Subtitle Edit can make 4k sup, but its support for special effects subtitles is not good.

Personally, I just want to make a 4k sup and I don't want to blurry text edges becasue the upscale , I just play it with movie on my pc, although the .ass is also a good choice. And I see some guys on forum.doom9.org also want to it to support 4k. Maybe they just like this type(.sup) or they don't want to other people to modifiy them.

So if it's not difficult to add this new feature, supporting 4k will be a cool thing.

**Comment by cubicibo** [comment]
And how would you convert the 4K BDN to SUP? Unfortunately, adding 4K support to SUPer is a really nontrivial task and a lot of code has to be changed.

If you have other options to convert to SUP, why not. But if you expect SUPer to work, it will not happen.

**Comment by dadlklk** [comment]
Use subtitle edit more like 'remake', not 'convert', because it doesn't support ass tags.

A lot of effects can't be reached.

**Comment by cubicibo** [comment]
I am not sure I underatand your last message correctly.
`ASS -[ass2bdnxml]-> 4K BDN -[SubtitleEdit]-> 4K SUP` will not work, if you have any effect in ASS?

If that pipeline does not work, then I am afraid that is a hopeless case.

**Comment by dadlklk** [comment]
use ass2bdnxml export BDN, then use it covert to sup by (SUPer or easySup or something else, they all depend on ass2bdnxml)
In my opinion, If the BDN which generated by ass2bdnxml is not 4k parameterized, then the converted SUP is not 4k either. Is that correct? So I think maybe you can make ass2bdnxml to support 4k.

[SubtitleEdit]-> 4K SUP is directly generating sup, it will be no step to generate a BDN or use BDN,
It can only simply be set with a few properties, and can not use tag like {\fscx0\t(0,600,\fscx100)\fscy0\t(0,600,\fscy100)\move(1864,1454,1916,1430,600,1550)}

![image](https://github.com/cubicibo/ass2bdnxml/assets/59605688/c56f1fc2-0d6e-403a-a713-b18d8eefaf97)

**Comment by cubicibo** [comment]
If easySUP or Spp2pgs work for you then I will add 4K support to ass2bdnxml.

However, SUPer will not support 4K. It is just not designed for that.

**Comment by cubicibo** [comment]
@dadlklk 2b91d11bacc8c0db75c269bd83f887d79ae5e569
a2b v0.7c will be published sometime later. Closing the issue. Again, do note SUPer will NOT support 2160p files.
